{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001E121165190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /studentDetails (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E121165190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /studentDetails (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E121165190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_add_multiple", "rerun": "0"}}, "suite_name": "test_Add_student_multiple_data.py"}}}, "date": "June 20, 2022", "start_time": 1655720798.3484063, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}